CREATE OR REPLACE VIEW VIEW_INQ_CLAIMS AS
SELECT 
	t15.ID_KEY,
    t15.CREATE_ON,
    t15.TX_TYPE,
    t15.TX_VOUCHER_ID,
    t15.TX_COVER_ID,
    t15.TX_CLIENT_ID,
    (select m5.CLI_NAME from MA0005 m5 where t15.TX_CLIENT_ID = m5.CLI_CODE) TX_CLIENT_CODE,
    '' TX_INS_ID,
    '' TX_INS_CODE,
    t15.TX_POLICY_NO,
    t15.TX_INTEREST,
    t15.TX_PARTY_NAME,
    t15.TX_CURR_ID,
    t15.TX_SUM_INS,
    t15.TX_DATA_STATUS,
    t15.TX_ADVICE_DATE,
    m14.PA_CHILD_DESC TX_DATA_STATUS_VAL
FROM TR0015 t15, MA0014 m14
	WHERE m14.PA_PARENT_CODE = 'STDATA'
    and m14.PA_CHILD_VALUE = t15.TX_DATA_STATUS;