CREATE OR REPLACE VIEW `VIEW_INQ_UPLOAD_TREATY` AS SELECT
    `T6`.`ID_KEY` AS `ID_KEY`,
    `T6`.`TRX_VOUCHER_ID` AS `TRX_VOUCHER_ID`,
    `T6`.`TRX_CLIENT` AS `TRX_CLIENT`,
    `M`.`CLI_NAME` AS `CLI_NAME`,
    `T6`.`TRX_CURR_ID` AS `TRX_CURR_ID`,
    `T6`.`TRX_TSI_AMOUNT` AS `TRX_TSI_AMOUNT`,
    `T6`.`CREATE_BY` AS `CREATE_BY`,
    `T6`.`CREATE_ON` AS `CREATE_ON`,
    (
    SELECT
        `T6Y`.`TRX_REMARKS`
    FROM
        `TR0006` `T6Y`
    WHERE
        `T6Y`.`TRX_VOUCHER_ID` = `T6`.`TRX_VOUCHER_ID`
    GROUP BY
        `T6Y`.`TRX_VOUCHER_ID`
) AS `TRX_DESCRIPTION`,
(
    SELECT
        `T6JX`.`TRX_INS_START`
    FROM
        `TR0006J` `T6JX`
    WHERE
        `T6JX`.`TRX_INS_START` IS NOT NULL AND `T6JX`.`TRX_VOUCHER_ID` = `T6`.`TRX_VOUCHER_ID`
    GROUP BY
        `T6JX`.`TRX_VOUCHER_ID`
) AS `TRX_INS_START`,
(
    SELECT
        DATE_FORMAT(`T6JY`.`TRX_INS_START`, '%d/%m/%Y')
    FROM
        `TR0006J` `T6JY`
    WHERE
        `T6JY`.`TRX_INS_START` IS NOT NULL AND `T6JY`.`TRX_VOUCHER_ID` = `T6`.`TRX_VOUCHER_ID`
    GROUP BY
        `T6JY`.`TRX_VOUCHER_ID`
) AS `TRX_INS_START_STR`,
(
    SELECT
        `T6JZ`.`TRX_INS_END`
    FROM
        `TR0006J` `T6JZ`
    WHERE
        `T6JZ`.`TRX_INS_END` IS NOT NULL AND `T6JZ`.`TRX_VOUCHER_ID` = `T6`.`TRX_VOUCHER_ID`
    GROUP BY
        `T6JZ`.`TRX_VOUCHER_ID`
) AS `TRX_INS_END`,
(
    SELECT
        DATE_FORMAT(`T6JW`.`TRX_INS_END`, '%d/%m/%Y')
    FROM
        `TR0006J` `T6JW`
    WHERE
        `T6JW`.`TRX_INS_END` IS NOT NULL AND `T6JW`.`TRX_VOUCHER_ID` = `T6`.`TRX_VOUCHER_ID`
    GROUP BY
        `T6JW`.`TRX_VOUCHER_ID`
) AS `TRX_INS_END_STR`,
(
    SELECT
        `T6X`.`TRX_TRX_ID`
    FROM
        `TR0006` `T6X`
    WHERE
        `T6X`.`TRX_VOUCHER_ID` = `T6`.`TRX_VOUCHER_ID`
    GROUP BY
        `T6X`.`TRX_VOUCHER_ID`
) AS `TRX_TRX_ID`
FROM
    (
        (`TR0006` `T6`
    JOIN `MA0005` `M`)
    JOIN `TR0006J` `T6J`
    )
WHERE
    `T6`.`TRX_DATA_STATUS` = '11' AND `T6`.`TRX_CLIENT` = `M`.`CLI_CODE` AND `T6`.`TRX_CLASS` = 'TRE' AND `T6`.`TRX_VOUCHER_ID` = `T6J`.`TRX_VOUCHER_ID` AND `T6`.`TRX_TRX_ID` = `T6J`.`TRX_TRX_ID` AND `T6J`.`TRX_NON_PRO` = 'P'
GROUP BY
    `T6`.`TRX_VOUCHER_ID`;