CREATE OR REPLACE VIEW `VIEW_INQ_PRODUCTION` AS SELECT
    `TR6`.`ID_KEY` AS `ID_KEY`,
    `TR6`.`TRX_CLASS` AS `TRX_CLASS`,
    `TR6`.`TRX_VOUCHER_ID` AS `REQUEST_ID`,
    `CLI`.`CLI_NAME` AS `CLIENT`,
    (
    SELECT DISTINCT
        `TR6A`.`TRX_COVER_CODE`
    FROM
        `TR0006A` `TR6A`
    WHERE
        `TR6`.`TRX_VOUCHER_ID` = `TR6A`.`TRX_VOUCHER_ID` AND `TR6`.`TRX_TRX_ID` = `TR6A`.`TRX_TRX_ID`
) AS `TYPE_OF_COVER`,
`TR6`.`TRX_CURR_ID` AS `CURR`,
`TR6`.`TRX_SUM_INSURED` AS `AMOUNT`,
`TR6`.`TRX_DATA_STATUS` AS `TRX_DATA_STATUS`,
CASE WHEN `TR6`.`TRX_DATA_STATUS` = 0 THEN 'New' WHEN `TR6`.`TRX_DATA_STATUS` = 3 THEN 'Placing Slip' WHEN `TR6`.`TRX_DATA_STATUS` = 5 THEN 'Quotation' WHEN `TR6`.`TRX_DATA_STATUS` = 11 THEN 'Closing' ELSE ''
END AS `STATUS`,
`TR6`.`CREATE_BY` AS `CREATE_BY`,
`TR6`.`CREATE_ON` AS `CREATE_ON`,
(
    SELECT DISTINCT
        `TR6J`.`TRX_NON_PRO`
    FROM
        `TR0006J` `TR6J`
    WHERE
        `TR6J`.`TRX_CLASS` = `TR6`.`TRX_CLASS` AND `TR6J`.`TRX_TRX_ID` = `TR6`.`TRX_TRX_ID` AND `TR6J`.`TRX_VOUCHER_ID` = `TR6`.`TRX_VOUCHER_ID` AND `TR6`.`TRX_CLASS` = 'TRE'
) AS `TRX_NON_PRO`,
(
    SELECT
        MAX(`TR6J`.`TRX_INS_START`)
    FROM
        `TR0006J` `TR6J`
    WHERE
        `TR6J`.`TRX_CLASS` = `TR6`.`TRX_CLASS` AND `TR6J`.`TRX_TRX_ID` = `TR6`.`TRX_TRX_ID` AND `TR6J`.`TRX_VOUCHER_ID` = `TR6`.`TRX_VOUCHER_ID` AND `TR6`.`TRX_CLASS` = 'TRE'
) AS `TRE_INS_START`,
(
    SELECT
        MAX(`TR6J`.`TRX_INS_END`)
    FROM
        `TR0006J` `TR6J`
    WHERE
        `TR6J`.`TRX_CLASS` = `TR6`.`TRX_CLASS` AND `TR6J`.`TRX_TRX_ID` = `TR6`.`TRX_TRX_ID` AND `TR6J`.`TRX_VOUCHER_ID` = `TR6`.`TRX_VOUCHER_ID` AND `TR6`.`TRX_CLASS` = 'TRE'
) AS `TRE_INS_END`,
(
    SELECT
        SUM(`TR6J`.`TRX_PREMIUM_AMT`)
    FROM
        `TR0006J` `TR6J`
    WHERE
        `TR6J`.`TRX_CLASS` = `TR6`.`TRX_CLASS` AND `TR6J`.`TRX_TRX_ID` = `TR6`.`TRX_TRX_ID` AND `TR6J`.`TRX_VOUCHER_ID` = `TR6`.`TRX_VOUCHER_ID` AND `TR6`.`TRX_CLASS` = 'TRE'
) AS `TRE_ADJ_AMOUNT`,
CASE WHEN `TR6`.`TRX_TRE_ADJ` = 0 THEN 'New' WHEN `TR6`.`TRX_TRE_ADJ` = 1 THEN 'Adjusted' ELSE ''
END AS `TRE_ADJ_STATUS`
FROM
    (
        `TR0006` `TR6`
    JOIN `MA0005` `CLI` ON
        (`CLI`.`CLI_CODE` = `TR6`.`TRX_CLIENT`)
    )
WHERE
    `TR6`.`TRX_DATA_STATUS` IN('0', '3', '5', '11');