CREATE OR REPLACE VIEW VIEW_INQ_SETTLEMENT AS 
	SELECT 
		TR12.ID_KEY, 
		TR12.TRX_TYPE,
		TR12.TRX_VOUCHER_ID, 
		(SELECT MAX(TR3.TRX_VOUCHER_ID) FROM TR0003 TR3 WHERE TR3.TRX_OLD_VOUCHER_ID = TR12.TRX_OLD_VOUCHER_ID AND TR3.TRX_CLIENT = TR12.TRX_CLIENT AND TR3.CREATE_ON = TR12.CREATE_ON) DC_NOTES_VOUCHER_ID,
		TR12.TRX_DATE, 
		TR12.TRX_DUE_DATE, 
		TR12.TRX_COUNT_INV, 
		TR12.TRX_CLIENT, 
		MA5.CLI_NAME, 
		TR12.TRX_COVER_CODE,
		TR12.TRX_DESCRIPTION, 
		TR12.TRX_CURR_ID,
		TR12.TRX_ORG_AMOUNT, 
		TR12.TRX_SET_AMOUNT, 
		TR12.TRX_INVC_AMOUNT, 
		TR12.TRX_COM_AMOUNT, 
		T6A.TRX_REMARKS,
		TR12.TRX_CURR_RATE 
				 FROM TR0012 TR12 LEFT JOIN (SELECT MAX(A.TRX_REMARKS) TRX_REMARKS, A.TRX_VOUCHER_ID FROM TR0006A A GROUP BY A.TRX_VOUCHER_ID) T6A
											 ON T6A.TRX_VOUCHER_ID = TR12.TRX_OLD_VOUCHER_ID, MA0005 MA5 
					 WHERE TR12.TRX_CLIENT = MA5.CLI_CODE 
					 AND TR12.TRX_DATA_STATUS = '11' 
					 -- AND TR12.TRX_INVC_AMOUNT > TR12.TRX_SET_AMOUNT
					 AND ((TR12.TRX_INVC_AMOUNT > 0 AND TR12.TRX_INVC_AMOUNT > TR12.TRX_SET_AMOUNT)
							OR (TR12.TRX_INVC_AMOUNT < 0 AND TR12.TRX_INVC_AMOUNT < TR12.TRX_SET_AMOUNT));