CREATE OR REPLACE VIEW `VIEW_INQ_DIRECT_MODIFY` AS SELECT
    `TR6`.`ID_KEY` AS `ID_KEY`,
    `TR6`.`TRX_CLASS` AS `TRX_CLASS`,
    `TR6`.`TRX_TRX_ID` AS `TRX_TRX_ID`,
    `TR6`.`TRX_VOUCHER_ID` AS `TRX_VOUCHER_ID`,
    `TR6A`.`TRX_COVER_CODE` AS `TRX_COVER_CODE`,
    `TR6`.`TRX_CLIENT` AS `TRX_CLIENT`,
    `CLI`.`CLI_NAME` AS `CLIENT_NAME`,
    `TR6`.`TRX_INSURED_NAME` AS `TRX_INSURED_NAME`,
    `TR6A`.`TRX_INS_START` AS `TRX_INS_START`,
    `TR6A`.`TRX_INS_END` AS `TRX_INS_END`,
    `TR6`.`TRX_CURR_ID` AS `TRX_CURR_ID`,
    `TR6`.`TRX_TSI_AMOUNT` AS `TRX_TSI_AMOUNT`,
    `TR6A`.`TRX_REMARKS` AS `TRX_REMARKS`,
    `TR6`.`TRX_DATA_STATUS` AS `TRX_DATA_STATUS`,
    CASE WHEN(
    SELECT
        SUM(`TR0012`.`TRX_SET_AMOUNT`)
    FROM
        `TR0012`
    WHERE
        `TR0012`.`TRX_OLD_VOUCHER_ID` = `TR6`.`TRX_VOUCHER_ID` AND `TR0012`.`TRX_OLD_TYPE` = `TR6`.`TRX_TRX_ID`
) = 0 THEN 'Available' ELSE 'Unavailable'
END AS `STATUS`,
`TR6`.`TRX_CLOSING_DATE` AS `TRX_CLOSING_DATE`
FROM
    (
        (`TR0006` `TR6`
    JOIN `TR0006A` `TR6A`)
    JOIN `MA0005` `CLI`
    )
WHERE
    `TR6`.`TRX_CLASS` = `TR6A`.`TRX_CLASS` AND `TR6`.`TRX_TRX_ID` = `TR6A`.`TRX_TRX_ID` AND `TR6`.`TRX_VOUCHER_ID` = `TR6A`.`TRX_VOUCHER_ID` AND `TR6`.`TRX_CLIENT` = `CLI`.`CLI_CODE` AND `TR6`.`TRX_CLASS` = 'FAC' AND `TR6`.`TRX_DATA_STATUS` = '11';